name: CI

on:
  push:
    tags:
      - "v*"
    branches: [ "main", "master"]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"

      - name: Run tests
        run: mvn -B clean test